# Python Fundamentals

In [11]:
import random 
import numpy as np

## Variables

In [17]:
a = 2.0
b = 3.0

a+b

5.0

## Lists

In [1]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [2]:
a[1]

2

Note indexes start from 0 in Python

Lists does not behave like mathematical objects, and that makes working with them for scientific computing very difficult. This is one of the main reasons (between others) why you will need to use ```numpy```. ```numpy``` define arrays so that they behave like mathematical objects.

In [3]:
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [10]:
a/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

Let's now try with numpy...

In [15]:
# We convert the list into numpy arrays
anp = np.array(a)
bnp = np.array(b)

print(anp)
print(bnp)

[1 2 3 4]
[5 6 7 8]


In [13]:
anp+bnp

array([ 6,  8, 10, 12])

In [14]:
anp*bnp

array([ 5, 12, 21, 32])

In [16]:
anp / 2.0

array([0.5, 1. , 1.5, 2. ])

## Example of loop with plain Python

In [21]:
lst1 = random.sample(range(1, 10**8), 10**7) 
lst2 = random.sample(range(1, 10**8), 10**7) 

In [22]:
%%time
ab = [lst1[i]*lst2[i] for i in range(len(lst1))] 

CPU times: user 1.94 s, sys: 17.7 ms, total: 1.96 s
Wall time: 1.96 s


## Example of loop with numpy

In [8]:
lst1 = random.sample(range(1, 10**8), 10**7) 
lst2 = random.sample(range(1, 10**8), 10**7) 
list1_np = np.array(lst1) 
list2_np = np.array(lst2) 


In [9]:
%%time
out2 = np.multiply(list1_np, list2_np) 

19.1 ms ± 524 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
